name: Terraform CI

on:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-ci.yml"
  push:
    branches: [dev]
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-ci.yml"

permissions:
  contents: write

jobs:
  fmt:
    name: Terraform Format
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - run: terraform fmt -recursive

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(terraform): auto-format"
          file_pattern: terraform/**/*.tf

  validate-plan:
    name: Terraform Validate & Plan
    runs-on: ubuntu-latest
    needs: fmt

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init (dev)
        run: terraform -chdir=terraform/dev init -reconfigure

      - name: Terraform Validate (dev)
        run: terraform -chdir=terraform/dev validate

      - name: Terraform Plan (dev, no lock)
        run: terraform -chdir=terraform/dev plan -lock=false -no-color
