name: Terraform CI

on:
  push:
    branches: [dev]
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-ci.yml"

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  fmt:
    name: Terraform Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: hashicorp/setup-terraform@v2
      - run: terraform fmt -recursive
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-format Terraform files"
          file_pattern: terraform/**/*.tf

  validate-plan:
    name: Validate & Plan
    runs-on: ubuntu-latest
    needs: fmt

    strategy:
      matrix:
        env: [dev, prod]

    steps:
      - uses: actions/checkout@v4.1.0
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform -chdir=terraform/${{ matrix.env }} init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Validate
        run: terraform -chdir=terraform/${{ matrix.env }} validate

      - name: Terraform Plan
        run: terraform -chdir=terraform/${{ matrix.env }} plan -no-color
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
